import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'

const benefits = ['Track expenses and income', 'AI insights about your habits', 'Goals, health, and reminders', 'Free forever for the basics']

function AuthPanel() {
  return <aside className="hidden w-2/5 flex-col justify-between bg-primary p-10 text-white lg:flex"><div><div className="flex items-center gap-2 font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/15">↗</span>RexpTrack</div><blockquote className="mt-16 text-2xl font-semibold leading-snug">“Your life, remembered and understood.”</blockquote><p className="mt-4 max-w-sm text-sm leading-6 text-[#9FE1CB]">Not just an expense tracker. A calm companion for your entire life journey.</p><ul className="mt-9 space-y-3 text-sm text-white/90">{benefits.map(item => <li key={item} className="flex gap-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-white/15 text-xs text-[#9FE1CB]">✓</span>{item}</li>)}</ul></div></aside>
}

export default function Login() {
  const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const { login } = useAuth(); const navigate = useNavigate()
  const submit = async (event) => { event.preventDefault(); setError(''); setSubmitting(true); try { await login(form.email, form.password); navigate('/dashboard') } catch (err) { setError(err.response?.data?.message || 'Unable to sign in. Check your details and try again.') } finally { setSubmitting(false) } }
  return <main className="grid min-h-screen bg-sand lg:grid-cols-[40%_60%]"><AuthPanel /><section className="flex items-center justify-center px-5 py-12"><form onSubmit={submit} className="w-full max-w-md"><Link to="/" className="mb-12 flex items-center gap-2 font-bold lg:hidden"><span className="brand-mark">↗</span>RexpTrack</Link><h1 className="text-3xl font-bold">Welcome back</h1><p className="mt-2 text-muted">Sign in to your RexpTrack account</p>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-7"><label className="field-label">Email</label><input className="field-input" type="email" placeholder="rahul@example.com" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div><div className="mt-4"><label className="field-label">Password</label><input className="field-input" type="password" placeholder="Enter your password" required value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></div><div className="mt-2 text-right text-sm font-medium text-primary">Forgot password?</div><button className="primary-button mt-5 w-full" disabled={submitting}>{submitting ? 'Signing in…' : 'Sign in to RexpTrack'}</button><div className="my-5 flex items-center gap-3 text-xs text-muted before:h-px before:flex-1 before:bg-line after:h-px after:flex-1 after:bg-line">or</div><button type="button" className="w-full rounded-lg border border-line bg-white py-2.5 text-sm font-medium">G&nbsp; Continue with Google</button><p className="mt-6 text-center text-sm text-muted">New to RexpTrack? <Link className="font-semibold text-primary" to="/register">Create a free account</Link></p></form></section></main>
}
