import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import { useAuth } from '../context/AuthContext'

const benefits = ['Free to start, no credit card', 'AI companion from day one', 'Private and secure by design', 'Cancel or delete anytime']

export default function Register() {
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const { register } = useAuth(); const navigate = useNavigate()
  const submit = async (event) => { event.preventDefault(); setError(''); setSubmitting(true); try { await register(form.name, form.email, form.password); navigate('/dashboard') } catch (err) { setError(err.response?.data?.message || 'Unable to create your account. Please try again.') } finally { setSubmitting(false) } }
  return <main className="grid min-h-screen bg-sand lg:grid-cols-[40%_60%]"><aside className="hidden bg-primary p-10 text-white lg:block"><div className="flex items-center gap-2 font-bold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-white/15">↗</span>RexpTrack</div><h2 className="mt-16 text-2xl font-semibold leading-snug">“Your second brain starts here.”</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[#9FE1CB]">Join thousands building healthier financial habits with AI-powered guidance.</p><ul className="mt-9 space-y-3 text-sm text-white/90">{benefits.map(item => <li key={item} className="flex gap-3"><span className="grid h-5 w-5 place-items-center rounded-full bg-white/15 text-xs text-[#9FE1CB]">✓</span>{item}</li>)}</ul></aside><section className="flex items-center justify-center px-5 py-12"><form onSubmit={submit} className="w-full max-w-md"><Link to="/" className="mb-12 flex items-center gap-2 font-bold lg:hidden"><span className="brand-mark">↗</span>RexpTrack</Link><h1 className="text-3xl font-bold">Create account</h1><p className="mt-2 text-muted">Start tracking smarter with RexpTrack</p>{error && <p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{[['Full name', 'name', 'text', 'Rahul Varma'], ['Email', 'email', 'email', 'rahul@example.com'], ['Password', 'password', 'password', 'Min 8 characters']].map(([label, name, type, placeholder]) => <div className="mt-4" key={name}><label className="field-label">{label}</label><input className="field-input" type={type} placeholder={placeholder} minLength={name === 'password' ? 8 : undefined} required value={form[name]} onChange={e => setForm({ ...form, [name]: e.target.value })} /></div>)}<button className="primary-button mt-6 w-full" disabled={submitting}>{submitting ? 'Creating account…' : 'Create free account'}</button><div className="my-5 flex items-center gap-3 text-xs text-muted before:h-px before:flex-1 before:bg-line after:h-px after:flex-1 after:bg-line">or</div><button type="button" className="w-full rounded-lg border border-line bg-white py-2.5 text-sm font-medium">G&nbsp; Continue with Google</button><p className="mt-6 text-center text-sm text-muted">Already have an account? <Link className="font-semibold text-primary" to="/login">Sign in</Link></p></form></section></main>
}
